#!/bin/sh

set -e

BUILDDIR=$1

test -z "$BUILDDIR" && BUILDDIR=build

VERSION=`grep 'version:' meson.build  | head -1 | awk '{print $2}' | sed -e "s/'//g" -e "s/,//"`
DISTNAME=gtk-vnc-$VERSION
DISTDIR=$BUILDDIR/$DISTNAME

rm -rf $DISTDIR
mkdir -p $DISTDIR

git clone --shared . $DISTDIR
rm -rf $DISTDIR/.git

for p in subprojects/*
do
    git clone --shared $p $DISTDIR/$p
    rm -rf $DISTDIR/$p/.git
done

build-aux/gitlog-to-changelog > $DISTDIR/ChangeLog

out="`git log --pretty=format:'   %aN <%aE>' | sort -u`"
perl -p -e "s/#authorslist#// and print '$out'" < AUTHORS.in > $DISTDIR/AUTHORS
rm -f $DISTDIR/AUTHORS.in

perl -p -e "s/\@VERSION\@/$VERSION/" gtk-vnc.spec.in > $DISTDIR/gtk-vnc.spec

cd $BUILDDIR
tar Jcf $DISTNAME.tar.xz $DISTNAME/
rm -rf $DISTNAME

echo "Created $DISTDIR.tar.xz"
